services:
  - type: web
    name: naturalfoods-backend
    env: python
    rootDir: backend/backend/backend
    buildCommand: ./build.sh
    startCommand: gunicorn backend.wsgi:application --workers=4 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "*.onrender.com,project-naturalfoods.onrender.com"
