# Generated by Django 6.0.6 on 2026-07-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Unit of measure (e.g. kg, lb, pcs)', max_length=50),
        ),
    ]
